# syntax=docker/dockerfile:1
ARG TARGETARCH

FROM scratch AS base

# Docker client for Docker-out-of-Docker: the daemon stays on the host,
# reached through the socket bind-mounted in docker-compose.yml.
# ~/.docker/cli-plugins is the user-level plugin directory the Docker CLI
# searches by default (highest priority), so no extra config is needed.

# Docker
COPY --link --from=docker:latest \
  /usr/local/bin/docker \
  /home/ubuntu/.local/bin/docker

# Docker plugins
COPY --link --from=docker:latest \
  /usr/local/libexec/docker/cli-plugins/ \
  /home/ubuntu/.docker/cli-plugins/

COPY --link \
  docker-entrypoint.sh \
  /home/ubuntu/.local/bin/docker-entrypoint

# OpenSSH server configuration
COPY --link \
  sshd_config \
  /home/ubuntu/.local/sshd/sshd_config

# =============================================================================
# Install and configure system packages for all runtime stages.
# Host keys are generated by the openssh-server postinst in /etc/ssh. The
# unprivileged sshd (running as ubuntu) must read them, but not write them.
FROM buildpack-deps:26.04 AS root-install

COPY --from=base --chown=ubuntu:ubuntu /home/ubuntu/ /home/ubuntu/

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  rm -f /etc/apt/apt.conf.d/docker-clean && \
  echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache && \
  apt-get -qqy --fix-missing update && \
  apt-get -qqy --fix-missing dist-upgrade && \
  apt-get -qqy --fix-missing install --no-install-recommends \
    brotli \
    bubblewrap \
    ffmpeg \
    htop \
    jq \
    lz4 \
    nano \
    openssh-server \
    php-cli \
    ripgrep \
    rsync \
    sudo \
    systemd-standalone-sysusers \
    tmux \
    xz-utils \
    zip \
    zstd \
  && chown --verbose ubuntu:ubuntu /etc/ssh/ssh_host_*_key* && \
  chmod --verbose 400 /etc/ssh/ssh_host_*_key && \
  chmod --verbose 444 /etc/ssh/ssh_host_*_key.pub && \
  echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ubuntu && \
  chmod --verbose 440 /etc/sudoers.d/ubuntu && \
  chmod --verbose 500 /home/ubuntu/.local/bin/docker-entrypoint && \
  chmod --verbose 400 /home/ubuntu/.local/sshd/sshd_config

USER ubuntu

ENV PATH="/home/ubuntu/.local/bin:/home/ubuntu/.cargo/bin:$PATH" \
  BUN_INSTALL="/home/ubuntu/.local" \
  CARGO_HOME="/home/ubuntu/.cargo" \
  GOBIN="/home/ubuntu/.local/bin" \
  NVM_DIR="/home/ubuntu/.nvm" \
  RUSTUP_HOME="/home/ubuntu/.rustup" \
  SDKMAN_DIR="/home/ubuntu/.sdkman" \
  UV_COMPILE_BYTECODE=1 \
  UV_MALWARE_CHECK=1 \
  UV_MANAGED_PYTHON=1 \
  UV_PREVIEW_FEATURES="python-install-default" \
  UV_PYTHON="3.14" \
  UV_TORCH_BACKEND="cu132"

VOLUME /home

WORKDIR /home/ubuntu

ENTRYPOINT [ "docker-entrypoint" ]