networks:
  default:
    external: true
    name: gateway

volumes:
  home:

services:
  main:
    container_name: workspace
    hostname: rtx-workspace
    init: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build: .
    env_file:
      - .env.service
    ports:
      - target: 2222
        published: 2222
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: home
        target: /home
    user: ubuntu
    group_add:
      - ${DOCKER_GID:-990}
    working_dir: /home/ubuntu
