#!/bin/bash

# Fail on errors, unset vars, and pipefail for robust startup
set -euo pipefail

if [ "$(id -un)" != "ubuntu" ]; then
  echo "This entrypoint must be run as the ubuntu user." >&2
  exit 1
fi

cd "$HOME"

INSTALL_GH_VERSION="${INSTALL_GH_VERSION:-2.97.0}"
INSTALL_JAVA_VERSION="${INSTALL_JAVA_VERSION:-25.3.4+1.r25-graalce}"

UNAME_MACHINE="$(uname --machine)"
TARGETARCH="${TARGETARCH:-$(if [ "$UNAME_MACHINE" = "aarch64" ]; then echo "arm64"; else echo "amd64"; fi)}"

SSH_AUTHORIZED_KEYS_FILE="$HOME/.ssh/authorized_keys"

_curl() {
  curl --proto '=https' --tlsv1.2 --fail --silent --show-error --location "$@"
}

_log() {
  echo "[$(date --iso-8601=seconds)] $*"
}

setup_git() {
  local github_name
  local github_email

  git config --global credential.https://github.com.helper '!f() { echo "username=x-access-token"; echo "password=$GH_TOKEN"; }; f'
  git config --global url."https://github.com/".insteadOf "git@github.com:"

  if [ -z "${GH_TOKEN:-}" ]; then
    echo "GH_TOKEN is not set. Skipping GitHub setup."
    return
  fi

  gh auth status
  github_name="$(gh api user --jq '.name')"
  github_email="$(gh api user --jq '.email')"

  if [ -z "${GIT_AUTHOR_NAME:-}" ] || [ -z "${GIT_COMMITTER_NAME:-}" ]; then
    git config --global user.name "${github_name}"
  fi

  if [ -z "${GIT_AUTHOR_EMAIL:-}" ] || [ -z "${GIT_COMMITTER_EMAIL:-}" ]; then
    git config --global user.email "${github_email}"
  fi
}

write_bashrc_env() {
  local bash_env="$HOME/.bash_env"
  local entry
  local key
  local value

  # SSH login shells reach ~/.bashrc via Ubuntu's ~/.profile; the exports
  # live in ~/.bash_env so ~/.bashrc only carries a small source snippet.
  {
    echo "# Generated by docker-entrypoint at container start. Do not edit."
    while IFS= read -r -d '' entry; do
      key="${entry%%=*}"
      value="${entry#*=}"

      # Skip vars sshd/bash set themselves, shell bookkeeping, and the
      # entrypoint's own inputs (potentially multi-line).
      case "$key" in
        ''|HOME|USER|LOGNAME|SHELL|TERM|MAIL|PWD|OLDPWD|SHLVL|_|SSH_AUTHORIZED_KEY)
          continue
          ;;
      esac

      case "$value" in
        '')
          continue
          ;;
      esac

      printf 'export %s=%q\n' "$key" "$value"
    done < <(env -0)
  } > "$bash_env"

  chmod 600 "$bash_env"
}

setup_ssh() {
  local authorized_keys_tmp

  mkdir --parents "$HOME/.ssh"
  chmod --verbose 700 "$HOME/.ssh"

  if [ -n "${SSH_AUTHORIZED_KEY:-}" ]; then
    authorized_keys_tmp="$(mktemp "$HOME/.ssh/authorized_keys.XXXXXX")"
    printf '%s\n' "$SSH_AUTHORIZED_KEY" > "$authorized_keys_tmp"
    chmod --verbose 600 "$authorized_keys_tmp"

    if ! ssh-keygen -l -f "$authorized_keys_tmp" >/dev/null; then
      rm --force --verbose "$authorized_keys_tmp"
      echo "SSH_AUTHORIZED_KEY is not a valid SSH public key." >&2
      exit 1
    fi

    mv --verbose "$authorized_keys_tmp" "$SSH_AUTHORIZED_KEYS_FILE"
  elif [ ! -e "$SSH_AUTHORIZED_KEYS_FILE" ]; then
    install --mode=600 /dev/null "$SSH_AUTHORIZED_KEYS_FILE"
  fi

  chmod --verbose 600 "$SSH_AUTHORIZED_KEYS_FILE"
}

00_install_brew() {
  _log "Installing Homebrew..."
  _curl https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | NONINTERACTIVE=1 bash

  [ -s "/home/linuxbrew/.linuxbrew/bin/brew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv bash)"
}

01_install_claude() {
  _log "Installing Claude Code..."
  _curl https://claude.ai/install.sh | bash
}

00_install_composer() {
  local expected_checksum
  local actual_checksum

  _log "Installing Composer..."
  _curl https://getcomposer.org/installer | php -- --install-dir=$HOME/.local/bin --filename=composer
}

01_install_gh() {
  _log "Installing GitHub CLI..."
  mkdir --parents $HOME/.local/gh

  _curl "https://github.com/cli/cli/releases/download/v${INSTALL_GH_VERSION}/gh_${INSTALL_GH_VERSION}_linux_${TARGETARCH}.tar.gz" | tar --directory=$HOME/.local/gh --strip-components=1 -xzf -
  ln --verbose --symbolic $HOME/.local/gh/bin/* $HOME/.local/bin/
}

01_install_yq() {
  _log "Installing yq..."
  mkdir --parents "$HOME/.local/yq"

  # Follow the latest upstream release for slim image bootstraps.
  _curl "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_${TARGETARCH}.tar.gz" | tar --directory="$HOME/.local/yq" -xzf -
  mv --verbose "$HOME/.local/yq/yq_linux_${TARGETARCH}" "$HOME/.local/yq/yq"
  ln --verbose --symbolic "$HOME/.local/yq/yq" "$HOME/.local/bin/yq"
}

00_install_nvm() {
  _log "Installing NVM..."
  _curl https://raw.githubusercontent.com/nvm-sh/nvm/HEAD/install.sh | bash

  [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

  _log "Installing latest Node.js..."
  nvm install node

  _log "Installing latest npm..."
  nvm install-latest-npm

  _log "Installing global npm packages..."
  npm install --global --allow-scripts=@fission-ai/openspec \
    corepack@latest \
    @fission-ai/openspec@latest \
    @mockoon/cli
  
  _log "Installing global package managers..."
  corepack install --global \
    pnpm@latest \
    yarn@latest
}

01_install_opencode() {
  _log "Installing OpenCode..."
  _curl https://opencode.ai/install | bash -s -- --no-modify-path
  ln --verbose --symbolic ${HOME}/.opencode/bin/* ${HOME}/.local/bin/
}

00_install_sdkman() {
  _log "Installing SDKMAN..."
  _curl https://get.sdkman.io | bash

  if [ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]; then
    set +euo pipefail
    source "${SDKMAN_DIR}/bin/sdkman-init.sh"

    sdk install java ${INSTALL_JAVA_VERSION}
    sdk install gradle
    sdk install kotlin
    sdk install maven
    sdk install quarkus
    sdk install scala
    set -euo pipefail
  fi
}

00_install_uv() {
  _log "Installing UV..."
  _curl https://astral.sh/uv/install.sh | bash

  _log "Installing Python"
  uv python install --default

  _log "Installing graphifyy..."
  uv tool install graphifyy

  _log "Installing ruff..."
  uv tool install ruff

  _log "Installing ty..."
  uv tool install ty
}

install_everything() {
  00_install_brew
  00_install_composer
  00_install_nvm
  00_install_sdkman
  00_install_uv

  01_install_claude
  01_install_gh
  01_install_opencode
  01_install_yq
}


write_bashrc_env
install_everything
setup_git
setup_ssh
