#!/bin/bash

# Fail on errors, unset vars, and pipefail for robust startup
set -euo pipefail

if [ "$(id -un)" != "ubuntu" ]; then
  echo "This entrypoint must be run as the ubuntu user." >&2
  exit 1
fi

cd "$HOME"

UNAME_MACHINE="$(uname -m)"
TARGETARCH="${TARGETARCH:-$(if [ "$UNAME_MACHINE" = "aarch64" ]; then echo "arm64"; else echo "amd64"; fi)}"

SSH_AUTHORIZED_KEYS_FILE="$HOME/.ssh/authorized_keys"
SSHD_DIR="$HOME/.local/sshd"
SSHD_PORT="${SSHD_PORT:-2222}"

validate_ssh_port() {
  case "$SSHD_PORT" in
    ''|*[!0-9]*)
      echo "SSHD_PORT must be an integer between 1024 and 65535." >&2
      exit 1
      ;;
  esac

  if [ "${#SSHD_PORT}" -gt 5 ] || [ "$SSHD_PORT" -lt 1024 ] || [ "$SSHD_PORT" -gt 65535 ]; then
    echo "SSHD_PORT must be an integer between 1024 and 65535." >&2
    exit 1
  fi

  export SSHD_PORT
}

setup_github_workspace() {
  local github_name
  local github_email

  if [ -z "${GH_TOKEN:-}" ]; then
    echo "GH_TOKEN is not set. Skipping GitHub workspace setup."
    return
  fi

  gh auth status
  github_name="$(gh api user --jq '.name')"
  github_email="$(gh api user --jq '.email')"

  if [ -z "${GIT_AUTHOR_NAME:-}" ] || [ -z "${GIT_COMMITTER_NAME:-}" ]; then
    git config --global user.name "${github_name}"
  fi

  if [ -z "${GIT_AUTHOR_EMAIL:-}" ] || [ -z "${GIT_COMMITTER_EMAIL:-}" ]; then
    git config --global user.email "${github_email}"
  fi

}

write_bashrc_env() {
  local bash_env="$HOME/.bash_env"
  local entry
  local key
  local value

  # SSH login shells reach ~/.bashrc via Ubuntu's ~/.profile; the exports
  # live in ~/.bash_env so ~/.bashrc only carries a small source snippet.
  {
    echo "# Generated by docker-entrypoint at container start. Do not edit."
    while IFS= read -r -d '' entry; do
      key="${entry%%=*}"
      value="${entry#*=}"

      # Skip vars sshd/bash set themselves, shell bookkeeping, and the
      # entrypoint's own inputs (potentially multi-line).
      case "$key" in
        ''|HOME|USER|LOGNAME|SHELL|TERM|MAIL|PWD|OLDPWD|SHLVL|_|SSH_AUTHORIZED_KEY)
          continue
          ;;
      esac

      case "$value" in
        '')
          continue
          ;;
      esac

      printf 'export %s=%q\n' "$key" "$value"
    done < <(env -0)
  } > "$bash_env"

  chmod 600 "$bash_env"
}

setup_bash_env() {
  local bash_env="$HOME/.bash_env"
  local bashrc="$HOME/.bashrc"
  local bashrc_tmp

  # Insert the snippet right above the interactive guard, after the file
  # header; "don.t" avoids the apostrophe inside the single-quoted pattern.
  # Custom .bashrc files without the guard comment fall back to prepending.
  if ! grep -q '^# >>> container environment >>>$' "$bashrc" 2>/dev/null; then
    if [ -f "$bashrc" ] && grep -q '^# If not running interactively, don.t do anything$' "$bashrc"; then
      sed -i '\|^# If not running interactively, don.t do anything$|i # >>> container environment >>>\n[ -f "$HOME/.bash_env" ] && . "$HOME/.bash_env"\n# <<< container environment <<<' "$bashrc"
    else
      bashrc_tmp="$(mktemp "$bashrc.XXXXXX")"
      {
        echo '# >>> container environment >>>'
        echo '[ -f "$HOME/.bash_env" ] && . "$HOME/.bash_env"'
        echo '# <<< container environment <<<'
        [ ! -f "$bashrc" ] || cat "$bashrc"
      } > "$bashrc_tmp"
      mv "$bashrc_tmp" "$bashrc"
    fi
  fi
}

setup_ssh_server() {
  local authorized_keys_tmp

  setup_bash_env
  validate_ssh_port

  mkdir --parents "$HOME/.ssh" "$SSHD_DIR"
  chmod 700 "$HOME/.ssh" "$SSHD_DIR"

  if [ -n "${SSH_AUTHORIZED_KEY:-}" ]; then
    authorized_keys_tmp="$(mktemp "$HOME/.ssh/authorized_keys.XXXXXX")"
    printf '%s\n' "$SSH_AUTHORIZED_KEY" > "$authorized_keys_tmp"
    chmod 600 "$authorized_keys_tmp"

    if ! ssh-keygen -l -f "$authorized_keys_tmp" >/dev/null; then
      rm -f "$authorized_keys_tmp"
      echo "SSH_AUTHORIZED_KEY is not a valid SSH public key." >&2
      exit 1
    fi

    mv "$authorized_keys_tmp" "$SSH_AUTHORIZED_KEYS_FILE"
  elif [ ! -e "$SSH_AUTHORIZED_KEYS_FILE" ]; then
    install --mode=600 /dev/null "$SSH_AUTHORIZED_KEYS_FILE"
  fi

  chmod 600 "$SSH_AUTHORIZED_KEYS_FILE"

  /usr/sbin/sshd \
    -t \
    -f "$SSHD_DIR/sshd_config" \
    -o "Port=$SSHD_PORT"
}

start_ssh_server() {
  validate_ssh_port

  exec /usr/sbin/sshd -D -e -f /home/ubuntu/.local/sshd/sshd_config -o Port=${SSHD_PORT}
}

_curl() {
  curl --proto '=https' --tlsv1.2 --fail --silent --show-error --location "$@"
}

_log() {
  echo "[$(date --iso-8601=seconds)] $*"
}

load_env() {
  if [ -z "${HOMEBREW_REPOSITORY:-}" ] && [ -s /home/linuxbrew/.linuxbrew/bin/brew ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv bash)"
  fi

  if [ -z "${NVM_BIN:-}" ] && [ -s "${NVM_DIR}/nvm.sh" ]; then
    source "${NVM_DIR}/nvm.sh"
  fi

  if [ -z "${SDKMAN_PLATFORM:-}" ] && [ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]; then
    set +euo pipefail
    source "${SDKMAN_DIR}/bin/sdkman-init.sh"
    set -euo pipefail
  fi
}

write_bashrc_env

setup_ssh_server

load_env

if [ "$#" -gt 0 ]; then
  exec "$@"
else
  start_ssh_server
fi
